name: Deploy to Heroku

on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku
      env: 
        HEROKU_API_KEY: bb5efc1f-b06a-4407-8e9e-b14feb2c4be0
      run: heroku container:login

    - name: Create Heroku
      env: 
        HEROKU_API_KEY: bb5efc1f-b06a-4407-8e9e-b14feb2c4be0
      run: heroku create
  
    - name: Push to Heroku
      env:
        HEROKU_API_KEY: bb5efc1f-b06a-4407-8e9e-b14feb2c4be0
      run: heroku container:push web

    - name: Release
      env:
        HEROKU_API_KEY: bb5efc1f-b06a-4407-8e9e-b14feb2c4be0
      run: heroku container:release web